[package]
name = "b-tree"
version = "0.1.0"
authors = ["code@tinychain.net"]
edition = "2021"
description = "A persistent B+ tree using freqfs"
license = "Apache-2.0"
readme = "README.md"
keywords = ["persistent", "ordered", "key", "key-value", "index", "collection"]
categories = ["database", "database-implementations", "data-structures"]

[[example]]
name = "example"

[dependencies]
collate = { path = "../collate" }
freqfs = { path = "../freqfs" }
futures = "0.3"
num_cpus = "1.15"
pin-project = "1.0"
safecast = "0.1"
uuid = "1.3"

[dev-dependencies]
async-trait = "0.1"
bytes = "1.4"
destream = "0.6"
destream_json = { version = "0.10", features=["tokio-io"] }
rand = "0.8"
tokio = { version = "1.25", features = ["macros"] }
tokio-util = { version = "0.7", features = ["io"] }
